<?php
return array(array("quest" => "将军", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "表哥", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "舞柳剑", "quest_type" => "寻", "exp_bonus" => 60),
    array("quest" => "红衣", "quest_type" => "寻", "exp_bonus" => 60),
    array("quest" => "顾云飞的秘函", "quest_type" => "寻", "exp_bonus" => 60),
    array("quest" => "叶孤鸿", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "白剑", "quest_type" => "寻", "exp_bonus" => 60),
    array("quest" => "粉燕子", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "铜钱镖", "quest_type" => "寻", "exp_bonus" => 60),
    array("quest" => "皮囊", "quest_type" => "寻", "exp_bonus" => 60),
    array("quest" => "「三才剑谱」", "quest_type" => "寻", "exp_bonus" => 60),
    array("quest" => "占卜入门", "quest_type" => "寻", "exp_bonus" => 60),
    array("quest" => "铁盒", "quest_type" => "寻", "exp_bonus" => 60),
    array("quest" => "怪兽", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "白额猛虎", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "方玉飞", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "冷若霜", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "银花青底披肩袍", "quest_type" => "寻", "exp_bonus" => 60),
    array("quest" => "蓝胡子", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "大牛", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "瞎子", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "风云衙役", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "杀威棒", "quest_type" => "寻", "exp_bonus" => 60),
    array("quest" => "风云差服", "quest_type" => "寻", "exp_bonus" => 60),
    array("quest" => "裸体男人", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "媒婆", "quest_type" => "杀", "exp_bonus" => 60),
    array("quest" => "龟奴", "quest_type" => "杀", "exp_bonus" => 60));
