<?php
return array(array("quest" => "珠宝商", "quest_type" => "杀", "exp_bonus" => 75),
    array("quest" => "云卒", "quest_type" => "杀", "exp_bonus" => 75),
    array("quest" => "碧玉胡刀", "quest_type" => "寻", "exp_bonus" => 75),
    array("quest" => "风云战甲", "quest_type" => "寻", "exp_bonus" => 75),
    array("quest" => "风兵", "quest_type" => "杀", "exp_bonus" => 75),
    array("quest" => "荆无命", "quest_type" => "杀", "exp_bonus" => 75),
    array("quest" => "参机大师", "quest_type" => "杀", "exp_bonus" => 75),
    array("quest" => "烈火孽龙", "quest_type" => "杀", "exp_bonus" => 75),
    array("quest" => "天缺古月寒", "quest_type" => "寻", "exp_bonus" => 75),
    array("quest" => "胸襟半开的轻纱丝袍", "quest_type" => "寻", "exp_bonus" => 75),
    array("quest" => "姬冰雁", "quest_type" => "杀", "exp_bonus" => 75),
    array("quest" => "溅满血的黑布袍", "quest_type" => "寻", "exp_bonus" => 75),
    array("quest" => "蓝小云", "quest_type" => "杀", "exp_bonus" => 75),
    array("quest" => "诸葛十一", "quest_type" => "杀", "exp_bonus" => 75),
    array("quest" => "小豆豆", "quest_type" => "杀", "exp_bonus" => 75),
    array("quest" => "管零", "quest_type" => "杀", "exp_bonus" => 75),
    array("quest" => "张剑", "quest_type" => "杀", "exp_bonus" => 75),
    array("quest" => "蝠王", "quest_type" => "杀", "exp_bonus" => 75));
