<?php
return array(array("quest" => "黑狗", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "铜钱镖", "quest_type" => "寻", "exp_bonus" => 40),
    array("quest" => "花寡妇", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "城卫", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "大红僧袍", "quest_type" => "寻", "exp_bonus" => 40),
    array("quest" => "三环禅杖", "quest_type" => "寻", "exp_bonus" => 40),
    array("quest" => "塔僧", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "东风", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "南风", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "西风", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "北风", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "红中", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "银护卫", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "黑色教服", "quest_type" => "寻", "exp_bonus" => 40),
    array("quest" => "王若钢", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "张似钢", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "李赛钢", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "赵如钢", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "黄色教服", "quest_type" => "寻", "exp_bonus" => 40),
    array("quest" => "考生", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "风云马褂", "quest_type" => "寻", "exp_bonus" => 40),
    array("quest" => "樊夫人", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "雪蹄胭脂马", "quest_type" => "杀", "exp_bonus" => 40),
    array("quest" => "牛皮马鞍", "quest_type" => "寻", "exp_bonus" => 40),
    array("quest" => "浪游诗人", "quest_type" => "杀", "exp_bonus" => 40));
