<?php
return array(array("quest" => "卖花姑娘", "quest_type" => "杀", "exp_bonus" => 30),
    array("quest" => "紫花瓣儿", "quest_type" => "寻", "exp_bonus" => 30),
    array("quest" => "狱卒", "quest_type" => "杀", "exp_bonus" => 30),
    array("quest" => "钝剑", "quest_type" => "寻", "exp_bonus" => 30),
    array("quest" => "护院", "quest_type" => "杀", "exp_bonus" => 30),
    array("quest" => "小短剑", "quest_type" => "寻", "exp_bonus" => 30),
    array("quest" => "小绵羊", "quest_type" => "杀", "exp_bonus" => 30),
    array("quest" => "知客道人", "quest_type" => "杀", "exp_bonus" => 30),
    array("quest" => "黄色道冠", "quest_type" => "寻", "exp_bonus" => 30),
    array("quest" => "彭长净", "quest_type" => "杀", "exp_bonus" => 30),
    array("quest" => "武林小豪杰", "quest_type" => "杀", "exp_bonus" => 30),
    array("quest" => "苗刀", "quest_type" => "寻", "exp_bonus" => 30),
    array("quest" => "迎客僧", "quest_type" => "杀", "exp_bonus" => 30),
    array("quest" => "云游僧人", "quest_type" => "杀", "exp_bonus" => 30),
    array("quest" => "极乐逍遥散", "quest_type" => "寻", "exp_bonus" => 30),
    array("quest" => "化尸粉", "quest_type" => "寻", "exp_bonus" => 30),
    array("quest" => "夜行衣", "quest_type" => "寻", "exp_bonus" => 30),
    array("quest" => "精钢飞刀", "quest_type" => "寻", "exp_bonus" => 30),
    array("quest" => "红嘴小麻雀", "quest_type" => "杀", "exp_bonus" => 30),
    array("quest" => "老屋人", "quest_type" => "杀", "exp_bonus" => 30),
    array("quest" => "鳄鱼", "quest_type" => "杀", "exp_bonus" => 30),
    array("quest" => "水蛇", "quest_type" => "杀", "exp_bonus" => 30),
    array("quest" => "金丝雀", "quest_type" => "杀", "exp_bonus" => 30));
