<?php
return array(array("quest" => "厨子", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "碧玉刀", "quest_type" => "寻", "exp_bonus" => 35),
    array("quest" => "护寺藏尼", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "大红尼袍", "quest_type" => "寻", "exp_bonus" => 35),
    array("quest" => "大绵羊", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "驼背老人", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "小翠", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "绣花鞋", "quest_type" => "寻", "exp_bonus" => 35),
    array("quest" => "粉红衫", "quest_type" => "寻", "exp_bonus" => 35),
    array("quest" => "细梅剑", "quest_type" => "寻", "exp_bonus" => 35),
    array("quest" => "道士", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "孙天灭", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "谢长勤", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "宋长清", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "金护卫", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "卤味儿", "quest_type" => "寻", "exp_bonus" => 35),
    array("quest" => "摺扇", "quest_type" => "寻", "exp_bonus" => 35),
    array("quest" => "舞蝶彩衫", "quest_type" => "寻", "exp_bonus" => 35),
    array("quest" => "大厨", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "雅公子", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "俏鸨母", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "关东大汉", "quest_type" => "杀", "exp_bonus" => 35),
    array("quest" => "血肠", "quest_type" => "寻", "exp_bonus" => 35));
